### ISSUE TITLE
About the formula: S = I+K*I

### ISSUE THREAD

**Issue by Max-Well-Wang** [hasibzunair/sharp-unets#1]
Hello dear author, I like your paper very much! I want to ask you a question. Should the result of the convolution of the input image **I** and the Laplacian filter kernel **K** be added to the pixels of the **I**?

**Comment by hasibzunair** [comment]
Hi @Max-Well-Wang! Yes, generally for images this is the case. But in our setup, we convolve each channel of the intermediate feature map with the kernel **K**. Please see Section 3.4 Sharp Blocks for details.
