### ISSUE TITLE
order

### ISSUE THREAD

**Issue by RockMan1966** [hasibzunair/sharp-unets#2]
W1 = build_sharp_blocks(conv4)
    # 2. Build depthwise convolutional layer with random weights
    sb1 = DepthwiseConv2D(kernel_size, use_bias=False, padding='same')
    # 3. Pass input to layer
    conv4 = sb1(conv4)
    # 4. Set filters as layer weights 
    sb1.set_weights([W1])
    # 5. Dont update weights
    sb1.trainable = False
    Hello, I have questions about this sequence, because I am not using tensorflow, I would like to ask. Why do you need to set the weight of sb1 after sending the feature map to sb1?
    I think is
     W1 = build_sharp_blocks(conv4)
    # 2. Build depthwise convolutional layer with random weights
    sb1 = DepthwiseConv2D(kernel_size, use_bias=False, padding='same')
    # 4. Set filters as layer weights 
    sb1.set_weights([W1])
    # 5. Dont update weights
    sb1.trainable = False
    # 3. Pass input to layer
    conv4 = sb1(conv4)

**Comment by hasibzunair** [comment]
Hi @RockMan1966, 

The weight is set with the filter values, think of it like hardcoding the values. And we do not want them to change, this is the Sharp Block which is show in Figure 2 in the [paper](https://arxiv.org/abs/2107.12461).
