### ISSUE TITLE
Can you upload the model function definition for your VGG-16 and ResNet-50 sharp U-Net models?

### ISSUE THREAD

**Issue by sivaramakrishnan-rajaraman** [hasibzunair/sharp-unets#4]
You have discussed the sharp U-Net with the ResNet-50 backbone gives the best performance in your study. Can you upload the model definitions for the VGG-16 and ResNet-50 Sharp U-Net models here? Thanks for your assistance.

**Comment by hasibzunair** [comment]
You can find them at https://github.com/hasibzunair/sharp-unet-experiments, specifically https://github.com/hasibzunair/sharp-unet-experiments/blob/master/segmentation_models/models/edgeunet.py
